version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s %(funcName)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: oulad_etl.log
    encoding: utf-8
    mode: w
loggers:
  oulad:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
root:
  level: INFO
  handlers: [ console, file ]
