name: CI

on:
  push:    { branches: [main] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:                    # lightweight MySQL for tests
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: root # pragma: allowlist secret
          MYSQL_DATABASE: oulad
        ports:   ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pre-commit (format, lint, type, tests)
        run: |
          poetry run pre-commit run --show-diff-on-failure --all-files
#          poetry run pytest --cov=oulad_etl --cov-report=xml
#
#      - name: Upload coverage
#        uses: codecov/codecov-action@v4
#        with: { file: ./coverage.xml }
